spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://AUTH
          predicates:
            - Path=/auth/**

        - id: a-service
          uri: lb://A-SERVICE
          predicates:
            - Path=/a/**

        - id: b-service
          uri: lb://B-SERVICE
          predicates:
            - Path=/b/**


  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/spring-keycloak/protocol/openid-connect/certs
          cache-time-to-live: 5s

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

