spring:
  cloud:
    gateway:
      routes:
        - id: admin
          uri: lb://ADMIN
          predicates:
            - Path=/admin/**

        - id: auth
          uri: lb://AUTH
          predicates:
            - Path=/auth/**

        - id: a-service
          uri: lb://A-SERVICE
          predicates:
            - Path=/a/**

        - id: b-service
          uri: lb://B-SERVICE
          predicates:
            - Path=/b/**

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/spring-keycloak/protocol/openid-connect/certs
          cache-time-to-live: 5s
      client:
        registration:
          keycloak:
            client-id: spring-service
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:7000/auth/api/v1/auth/login
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/spring-keycloak
            authorization-uri: http://localhost:8080/realms/spring-keycloak/protocol/openid-connect/auth
            token-uri: http://localhost:8080/realms/spring-keycloak/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/realms/spring-keycloak/protocol/openid-connect/userinfo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

